# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'NuevaInterfaz.ui'
#
# Created: Thu Feb 16 09:48:49 2017
#      by: PyQt4 UI code generator 4.10.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName(_fromUtf8("Dialog"))
        Dialog.resize(727, 567)
        self.gridLayout_2 = QtGui.QGridLayout(Dialog)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.tabPrincipal = QtGui.QTabWidget(Dialog)
        self.tabPrincipal.setObjectName(_fromUtf8("tabPrincipal"))
        self.tabAdministrarFichas = QtGui.QWidget()
        self.tabAdministrarFichas.setObjectName(_fromUtf8("tabAdministrarFichas"))
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.tabAdministrarFichas)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.tabOpFichas = QtGui.QTabWidget(self.tabAdministrarFichas)
        self.tabOpFichas.setObjectName(_fromUtf8("tabOpFichas"))
        self.tab_4 = QtGui.QWidget()
        self.tab_4.setObjectName(_fromUtf8("tab_4"))
        self.gridLayout = QtGui.QGridLayout(self.tab_4)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.label_3 = QtGui.QLabel(self.tab_4)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout.addWidget(self.label_3, 0, 0, 1, 1)
        self.cmbCategoria = QtGui.QComboBox(self.tab_4)
        self.cmbCategoria.setObjectName(_fromUtf8("cmbCategoria"))
        self.gridLayout.addWidget(self.cmbCategoria, 0, 1, 1, 1)
        self.lblCliente = QtGui.QLabel(self.tab_4)
        self.lblCliente.setObjectName(_fromUtf8("lblCliente"))
        self.gridLayout.addWidget(self.lblCliente, 1, 0, 1, 1)
        self.cmbCliente = QtGui.QComboBox(self.tab_4)
        self.cmbCliente.setObjectName(_fromUtf8("cmbCliente"))
        self.gridLayout.addWidget(self.cmbCliente, 1, 1, 1, 1)
        self.lblMaquina = QtGui.QLabel(self.tab_4)
        self.lblMaquina.setObjectName(_fromUtf8("lblMaquina"))
        self.gridLayout.addWidget(self.lblMaquina, 2, 0, 1, 1)
        self.cmbMaquina = QtGui.QComboBox(self.tab_4)
        self.cmbMaquina.setObjectName(_fromUtf8("cmbMaquina"))
        self.gridLayout.addWidget(self.cmbMaquina, 2, 1, 1, 1)
        self.lblPedido = QtGui.QLabel(self.tab_4)
        self.lblPedido.setObjectName(_fromUtf8("lblPedido"))
        self.gridLayout.addWidget(self.lblPedido, 3, 0, 1, 1)
        self.lePedido = QtGui.QLineEdit(self.tab_4)
        self.lePedido.setObjectName(_fromUtf8("lePedido"))
        self.gridLayout.addWidget(self.lePedido, 3, 1, 1, 1)
        self.lblEtiqueta = QtGui.QLabel(self.tab_4)
        self.lblEtiqueta.setObjectName(_fromUtf8("lblEtiqueta"))
        self.gridLayout.addWidget(self.lblEtiqueta, 4, 0, 1, 1)
        self.leEtiqueta = QtGui.QLineEdit(self.tab_4)
        self.leEtiqueta.setObjectName(_fromUtf8("leEtiqueta"))
        self.gridLayout.addWidget(self.leEtiqueta, 4, 1, 1, 1)
        self.lblFecha = QtGui.QLabel(self.tab_4)
        self.lblFecha.setObjectName(_fromUtf8("lblFecha"))
        self.gridLayout.addWidget(self.lblFecha, 5, 0, 1, 1)
        self.deFechaFicha = QtGui.QDateEdit(self.tab_4)
        self.deFechaFicha.setCalendarPopup(True)
        self.deFechaFicha.setObjectName(_fromUtf8("deFechaFicha"))
        self.gridLayout.addWidget(self.deFechaFicha, 5, 1, 1, 1)
        self.lblVelocidad_2 = QtGui.QLabel(self.tab_4)
        self.lblVelocidad_2.setObjectName(_fromUtf8("lblVelocidad_2"))
        self.gridLayout.addWidget(self.lblVelocidad_2, 6, 0, 1, 1)
        self.dsbVelocidadFicha = QtGui.QDoubleSpinBox(self.tab_4)
        self.dsbVelocidadFicha.setDecimals(2)
        self.dsbVelocidadFicha.setObjectName(_fromUtf8("dsbVelocidadFicha"))
        self.gridLayout.addWidget(self.dsbVelocidadFicha, 6, 1, 1, 1)
        self.lblClisses = QtGui.QLabel(self.tab_4)
        self.lblClisses.setObjectName(_fromUtf8("lblClisses"))
        self.gridLayout.addWidget(self.lblClisses, 7, 0, 1, 1)
        self.rbConvencionales = QtGui.QRadioButton(self.tab_4)
        self.rbConvencionales.setChecked(True)
        self.rbConvencionales.setObjectName(_fromUtf8("rbConvencionales"))
        self.gridLayout.addWidget(self.rbConvencionales, 7, 1, 1, 1)
        self.rbDigitales = QtGui.QRadioButton(self.tab_4)
        self.rbDigitales.setObjectName(_fromUtf8("rbDigitales"))
        self.gridLayout.addWidget(self.rbDigitales, 8, 1, 1, 1)
        self.pbGuardarFicha = QtGui.QPushButton(self.tab_4)
        self.pbGuardarFicha.setObjectName(_fromUtf8("pbGuardarFicha"))
        self.gridLayout.addWidget(self.pbGuardarFicha, 9, 0, 1, 2)
        self.tabOpFichas.addTab(self.tab_4, _fromUtf8(""))
        self.tabModificarficha = QtGui.QWidget()
        self.tabModificarficha.setObjectName(_fromUtf8("tabModificarficha"))
        self.verticalLayout_12 = QtGui.QVBoxLayout(self.tabModificarficha)
        self.verticalLayout_12.setObjectName(_fromUtf8("verticalLayout_12"))
        self.groupBox_2 = QtGui.QGroupBox(self.tabModificarficha)
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.verticalLayout_14 = QtGui.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_14.setObjectName(_fromUtf8("verticalLayout_14"))
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.cmbModificar = QtGui.QComboBox(self.groupBox_2)
        self.cmbModificar.setObjectName(_fromUtf8("cmbModificar"))
        self.cmbModificar.addItem(_fromUtf8(""))
        self.horizontalLayout_5.addWidget(self.cmbModificar)
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.rbModificarEtiqueta = QtGui.QRadioButton(self.groupBox_2)
        self.rbModificarEtiqueta.setChecked(True)
        self.rbModificarEtiqueta.setObjectName(_fromUtf8("rbModificarEtiqueta"))
        self.horizontalLayout_6.addWidget(self.rbModificarEtiqueta)
        self.rbModificarPorPedido = QtGui.QRadioButton(self.groupBox_2)
        self.rbModificarPorPedido.setAutoExclusive(False)
        self.rbModificarPorPedido.setObjectName(_fromUtf8("rbModificarPorPedido"))
        self.horizontalLayout_6.addWidget(self.rbModificarPorPedido)
        self.horizontalLayout_5.addLayout(self.horizontalLayout_6)
        self.verticalLayout_14.addLayout(self.horizontalLayout_5)
        self.tabModificarFicha = QtGui.QTabWidget(self.groupBox_2)
        self.tabModificarFicha.setObjectName(_fromUtf8("tabModificarFicha"))
        self.tabFicha_2 = QtGui.QWidget()
        self.tabFicha_2.setObjectName(_fromUtf8("tabFicha_2"))
        self.gridLayout_20 = QtGui.QGridLayout(self.tabFicha_2)
        self.gridLayout_20.setObjectName(_fromUtf8("gridLayout_20"))
        self.lblPedido_2 = QtGui.QLabel(self.tabFicha_2)
        self.lblPedido_2.setObjectName(_fromUtf8("lblPedido_2"))
        self.gridLayout_20.addWidget(self.lblPedido_2, 3, 0, 1, 1)
        self.lblEtiqueta_2 = QtGui.QLabel(self.tabFicha_2)
        self.lblEtiqueta_2.setObjectName(_fromUtf8("lblEtiqueta_2"))
        self.gridLayout_20.addWidget(self.lblEtiqueta_2, 4, 0, 1, 1)
        self.lblVelocidad_3 = QtGui.QLabel(self.tabFicha_2)
        self.lblVelocidad_3.setObjectName(_fromUtf8("lblVelocidad_3"))
        self.gridLayout_20.addWidget(self.lblVelocidad_3, 7, 0, 1, 1)
        self.lblMaquina_2 = QtGui.QLabel(self.tabFicha_2)
        self.lblMaquina_2.setObjectName(_fromUtf8("lblMaquina_2"))
        self.gridLayout_20.addWidget(self.lblMaquina_2, 2, 0, 1, 1)
        self.lblClisses_2 = QtGui.QLabel(self.tabFicha_2)
        self.lblClisses_2.setObjectName(_fromUtf8("lblClisses_2"))
        self.gridLayout_20.addWidget(self.lblClisses_2, 9, 0, 1, 1)
        self.cmbMaquinaMod = QtGui.QComboBox(self.tabFicha_2)
        self.cmbMaquinaMod.setObjectName(_fromUtf8("cmbMaquinaMod"))
        self.gridLayout_20.addWidget(self.cmbMaquinaMod, 2, 2, 1, 1)
        self.label_4 = QtGui.QLabel(self.tabFicha_2)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout_20.addWidget(self.label_4, 0, 0, 1, 1)
        self.cmbClienteMod = QtGui.QComboBox(self.tabFicha_2)
        self.cmbClienteMod.setObjectName(_fromUtf8("cmbClienteMod"))
        self.gridLayout_20.addWidget(self.cmbClienteMod, 1, 2, 1, 1)
        self.rbDigitalesMod = QtGui.QRadioButton(self.tabFicha_2)
        self.rbDigitalesMod.setObjectName(_fromUtf8("rbDigitalesMod"))
        self.gridLayout_20.addWidget(self.rbDigitalesMod, 10, 2, 1, 1)
        self.cmbCategoriaMod = QtGui.QComboBox(self.tabFicha_2)
        self.cmbCategoriaMod.setObjectName(_fromUtf8("cmbCategoriaMod"))
        self.gridLayout_20.addWidget(self.cmbCategoriaMod, 0, 2, 1, 1)
        self.dsbVelocidadFichaMod = QtGui.QDoubleSpinBox(self.tabFicha_2)
        self.dsbVelocidadFichaMod.setDecimals(2)
        self.dsbVelocidadFichaMod.setObjectName(_fromUtf8("dsbVelocidadFichaMod"))
        self.gridLayout_20.addWidget(self.dsbVelocidadFichaMod, 7, 2, 1, 1)
        self.lblCliente_2 = QtGui.QLabel(self.tabFicha_2)
        self.lblCliente_2.setObjectName(_fromUtf8("lblCliente_2"))
        self.gridLayout_20.addWidget(self.lblCliente_2, 1, 0, 1, 1)
        self.lblFecha_2 = QtGui.QLabel(self.tabFicha_2)
        self.lblFecha_2.setObjectName(_fromUtf8("lblFecha_2"))
        self.gridLayout_20.addWidget(self.lblFecha_2, 5, 0, 1, 1)
        self.lePedidoMod = QtGui.QLineEdit(self.tabFicha_2)
        self.lePedidoMod.setObjectName(_fromUtf8("lePedidoMod"))
        self.gridLayout_20.addWidget(self.lePedidoMod, 3, 2, 1, 1)
        self.deFechaFichaMod = QtGui.QDateEdit(self.tabFicha_2)
        self.deFechaFichaMod.setCalendarPopup(True)
        self.deFechaFichaMod.setObjectName(_fromUtf8("deFechaFichaMod"))
        self.gridLayout_20.addWidget(self.deFechaFichaMod, 5, 2, 1, 1)
        self.rbConvencionalesMod = QtGui.QRadioButton(self.tabFicha_2)
        self.rbConvencionalesMod.setChecked(True)
        self.rbConvencionalesMod.setObjectName(_fromUtf8("rbConvencionalesMod"))
        self.gridLayout_20.addWidget(self.rbConvencionalesMod, 9, 2, 1, 1)
        self.leEtiquetaMod = QtGui.QLineEdit(self.tabFicha_2)
        self.leEtiquetaMod.setObjectName(_fromUtf8("leEtiquetaMod"))
        self.gridLayout_20.addWidget(self.leEtiquetaMod, 4, 2, 1, 1)
        self.tabModificarFicha.addTab(self.tabFicha_2, _fromUtf8(""))
        self.tabMateriales_2 = QtGui.QWidget()
        self.tabMateriales_2.setObjectName(_fromUtf8("tabMateriales_2"))
        self.gridLayout_3 = QtGui.QGridLayout(self.tabMateriales_2)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.lblCodigoMaterial_2 = QtGui.QLabel(self.tabMateriales_2)
        self.lblCodigoMaterial_2.setObjectName(_fromUtf8("lblCodigoMaterial_2"))
        self.gridLayout_3.addWidget(self.lblCodigoMaterial_2, 0, 0, 1, 1)
        self.leCodigoMaterialMod = QtGui.QLineEdit(self.tabMateriales_2)
        self.leCodigoMaterialMod.setObjectName(_fromUtf8("leCodigoMaterialMod"))
        self.gridLayout_3.addWidget(self.leCodigoMaterialMod, 0, 1, 1, 1)
        self.lblNombreMaterial_2 = QtGui.QLabel(self.tabMateriales_2)
        self.lblNombreMaterial_2.setObjectName(_fromUtf8("lblNombreMaterial_2"))
        self.gridLayout_3.addWidget(self.lblNombreMaterial_2, 1, 0, 1, 1)
        self.leNombreMaterialMod = QtGui.QLineEdit(self.tabMateriales_2)
        self.leNombreMaterialMod.setObjectName(_fromUtf8("leNombreMaterialMod"))
        self.gridLayout_3.addWidget(self.leNombreMaterialMod, 1, 1, 1, 1)
        self.lblProveedorMaterial_2 = QtGui.QLabel(self.tabMateriales_2)
        self.lblProveedorMaterial_2.setObjectName(_fromUtf8("lblProveedorMaterial_2"))
        self.gridLayout_3.addWidget(self.lblProveedorMaterial_2, 2, 0, 1, 1)
        self.leProveedorMaterialMod = QtGui.QLineEdit(self.tabMateriales_2)
        self.leProveedorMaterialMod.setObjectName(_fromUtf8("leProveedorMaterialMod"))
        self.gridLayout_3.addWidget(self.leProveedorMaterialMod, 2, 1, 1, 1)
        self.lblAncho_2 = QtGui.QLabel(self.tabMateriales_2)
        self.lblAncho_2.setObjectName(_fromUtf8("lblAncho_2"))
        self.gridLayout_3.addWidget(self.lblAncho_2, 3, 0, 1, 1)
        self.dsbAnchoMaterialMod = QtGui.QDoubleSpinBox(self.tabMateriales_2)
        self.dsbAnchoMaterialMod.setDecimals(2)
        self.dsbAnchoMaterialMod.setObjectName(_fromUtf8("dsbAnchoMaterialMod"))
        self.gridLayout_3.addWidget(self.dsbAnchoMaterialMod, 3, 1, 1, 1)
        self.lblTC_2 = QtGui.QLabel(self.tabMateriales_2)
        self.lblTC_2.setObjectName(_fromUtf8("lblTC_2"))
        self.gridLayout_3.addWidget(self.lblTC_2, 4, 0, 1, 1)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.rbTC1Mod = QtGui.QRadioButton(self.tabMateriales_2)
        self.rbTC1Mod.setChecked(True)
        self.rbTC1Mod.setObjectName(_fromUtf8("rbTC1Mod"))
        self.horizontalLayout_2.addWidget(self.rbTC1Mod)
        self.rbTC2Mod = QtGui.QRadioButton(self.tabMateriales_2)
        self.rbTC2Mod.setObjectName(_fromUtf8("rbTC2Mod"))
        self.horizontalLayout_2.addWidget(self.rbTC2Mod)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.gridLayout_3.addLayout(self.horizontalLayout_2, 4, 1, 1, 1)
        self.viewMateriales = QtGui.QTableView(self.tabMateriales_2)
        self.viewMateriales.setObjectName(_fromUtf8("viewMateriales"))
        self.gridLayout_3.addWidget(self.viewMateriales, 5, 0, 1, 2)
        self.verticalLayout_11 = QtGui.QVBoxLayout()
        self.verticalLayout_11.setObjectName(_fromUtf8("verticalLayout_11"))
        self.pbAniadirMaterialMod = QtGui.QPushButton(self.tabMateriales_2)
        self.pbAniadirMaterialMod.setObjectName(_fromUtf8("pbAniadirMaterialMod"))
        self.verticalLayout_11.addWidget(self.pbAniadirMaterialMod)
        self.pbEditarMaterialMod = QtGui.QPushButton(self.tabMateriales_2)
        self.pbEditarMaterialMod.setObjectName(_fromUtf8("pbEditarMaterialMod"))
        self.verticalLayout_11.addWidget(self.pbEditarMaterialMod)
        self.pbBorrarMaterialMod = QtGui.QPushButton(self.tabMateriales_2)
        self.pbBorrarMaterialMod.setObjectName(_fromUtf8("pbBorrarMaterialMod"))
        self.verticalLayout_11.addWidget(self.pbBorrarMaterialMod)
        self.gridLayout_3.addLayout(self.verticalLayout_11, 5, 2, 1, 1)
        self.tabModificarFicha.addTab(self.tabMateriales_2, _fromUtf8(""))
        self.tabTintas_2 = QtGui.QWidget()
        self.tabTintas_2.setObjectName(_fromUtf8("tabTintas_2"))
        self.gridLayout_22 = QtGui.QGridLayout(self.tabTintas_2)
        self.gridLayout_22.setObjectName(_fromUtf8("gridLayout_22"))
        self.lblColor_3 = QtGui.QLabel(self.tabTintas_2)
        self.lblColor_3.setObjectName(_fromUtf8("lblColor_3"))
        self.gridLayout_22.addWidget(self.lblColor_3, 0, 0, 1, 1)
        self.leColorTintaMod = QtGui.QLineEdit(self.tabTintas_2)
        self.leColorTintaMod.setObjectName(_fromUtf8("leColorTintaMod"))
        self.gridLayout_22.addWidget(self.leColorTintaMod, 0, 2, 1, 1)
        self.lblTipoTinta_2 = QtGui.QLabel(self.tabTintas_2)
        self.lblTipoTinta_2.setObjectName(_fromUtf8("lblTipoTinta_2"))
        self.gridLayout_22.addWidget(self.lblTipoTinta_2, 1, 0, 1, 1)
        self.leTipoTintaMod = QtGui.QLineEdit(self.tabTintas_2)
        self.leTipoTintaMod.setObjectName(_fromUtf8("leTipoTintaMod"))
        self.gridLayout_22.addWidget(self.leTipoTintaMod, 1, 2, 1, 1)
        self.lblAniloxTinta_2 = QtGui.QLabel(self.tabTintas_2)
        self.lblAniloxTinta_2.setObjectName(_fromUtf8("lblAniloxTinta_2"))
        self.gridLayout_22.addWidget(self.lblAniloxTinta_2, 2, 0, 1, 1)
        self.leAniloxTintaMod = QtGui.QLineEdit(self.tabTintas_2)
        self.leAniloxTintaMod.setObjectName(_fromUtf8("leAniloxTintaMod"))
        self.gridLayout_22.addWidget(self.leAniloxTintaMod, 2, 2, 1, 1)
        self.lblProveedor_2 = QtGui.QLabel(self.tabTintas_2)
        self.lblProveedor_2.setObjectName(_fromUtf8("lblProveedor_2"))
        self.gridLayout_22.addWidget(self.lblProveedor_2, 3, 0, 1, 2)
        self.leProveedorTintaMod = QtGui.QLineEdit(self.tabTintas_2)
        self.leProveedorTintaMod.setObjectName(_fromUtf8("leProveedorTintaMod"))
        self.gridLayout_22.addWidget(self.leProveedorTintaMod, 3, 2, 1, 1)
        self.lblProveedor2_2 = QtGui.QLabel(self.tabTintas_2)
        self.lblProveedor2_2.setObjectName(_fromUtf8("lblProveedor2_2"))
        self.gridLayout_22.addWidget(self.lblProveedor2_2, 4, 0, 1, 2)
        self.leProveedorTinta2Mod = QtGui.QLineEdit(self.tabTintas_2)
        self.leProveedorTinta2Mod.setObjectName(_fromUtf8("leProveedorTinta2Mod"))
        self.gridLayout_22.addWidget(self.leProveedorTinta2Mod, 4, 2, 1, 1)
        self.lblProveedor3_2 = QtGui.QLabel(self.tabTintas_2)
        self.lblProveedor3_2.setObjectName(_fromUtf8("lblProveedor3_2"))
        self.gridLayout_22.addWidget(self.lblProveedor3_2, 5, 0, 1, 2)
        self.leProveedorTinta3Mod = QtGui.QLineEdit(self.tabTintas_2)
        self.leProveedorTinta3Mod.setObjectName(_fromUtf8("leProveedorTinta3Mod"))
        self.gridLayout_22.addWidget(self.leProveedorTinta3Mod, 5, 2, 1, 1)
        self.viewTintas = QtGui.QTableView(self.tabTintas_2)
        self.viewTintas.setObjectName(_fromUtf8("viewTintas"))
        self.gridLayout_22.addWidget(self.viewTintas, 6, 1, 3, 2)
        self.pbAniadirTintaMod = QtGui.QPushButton(self.tabTintas_2)
        self.pbAniadirTintaMod.setObjectName(_fromUtf8("pbAniadirTintaMod"))
        self.gridLayout_22.addWidget(self.pbAniadirTintaMod, 6, 3, 1, 1)
        self.pbEditarTintaMod = QtGui.QPushButton(self.tabTintas_2)
        self.pbEditarTintaMod.setObjectName(_fromUtf8("pbEditarTintaMod"))
        self.gridLayout_22.addWidget(self.pbEditarTintaMod, 7, 3, 1, 1)
        self.pbBorrarTintaMod = QtGui.QPushButton(self.tabTintas_2)
        self.pbBorrarTintaMod.setObjectName(_fromUtf8("pbBorrarTintaMod"))
        self.gridLayout_22.addWidget(self.pbBorrarTintaMod, 8, 3, 1, 1)
        self.tabModificarFicha.addTab(self.tabTintas_2, _fromUtf8(""))
        self.tabCaracteristicas_2 = QtGui.QWidget()
        self.tabCaracteristicas_2.setObjectName(_fromUtf8("tabCaracteristicas_2"))
        self.verticalLayout_13 = QtGui.QVBoxLayout(self.tabCaracteristicas_2)
        self.verticalLayout_13.setObjectName(_fromUtf8("verticalLayout_13"))
        self.tabModCarSec = QtGui.QTabWidget(self.tabCaracteristicas_2)
        self.tabModCarSec.setObjectName(_fromUtf8("tabModCarSec"))
        self.tabMallas_2 = QtGui.QWidget()
        self.tabMallas_2.setObjectName(_fromUtf8("tabMallas_2"))
        self.gridLayout_25 = QtGui.QGridLayout(self.tabMallas_2)
        self.gridLayout_25.setObjectName(_fromUtf8("gridLayout_25"))
        self.formularioMallaMod = QtGui.QFrame(self.tabMallas_2)
        self.formularioMallaMod.setFrameShape(QtGui.QFrame.StyledPanel)
        self.formularioMallaMod.setFrameShadow(QtGui.QFrame.Raised)
        self.formularioMallaMod.setObjectName(_fromUtf8("formularioMallaMod"))
        self.gridLayout_27 = QtGui.QGridLayout(self.formularioMallaMod)
        self.gridLayout_27.setObjectName(_fromUtf8("gridLayout_27"))
        self.lblTipo_3 = QtGui.QLabel(self.formularioMallaMod)
        self.lblTipo_3.setObjectName(_fromUtf8("lblTipo_3"))
        self.gridLayout_27.addWidget(self.lblTipo_3, 0, 0, 1, 1)
        self.leTipoMallaMod = QtGui.QLineEdit(self.formularioMallaMod)
        self.leTipoMallaMod.setObjectName(_fromUtf8("leTipoMallaMod"))
        self.gridLayout_27.addWidget(self.leTipoMallaMod, 0, 1, 1, 1)
        self.rbInterno_2 = QtGui.QRadioButton(self.formularioMallaMod)
        self.rbInterno_2.setChecked(True)
        self.rbInterno_2.setObjectName(_fromUtf8("rbInterno_2"))
        self.gridLayout_27.addWidget(self.rbInterno_2, 1, 0, 1, 2)
        self.rbExternoMod = QtGui.QRadioButton(self.formularioMallaMod)
        self.rbExternoMod.setObjectName(_fromUtf8("rbExternoMod"))
        self.gridLayout_27.addWidget(self.rbExternoMod, 2, 0, 1, 2)
        self.viewMalla = QtGui.QTableView(self.formularioMallaMod)
        self.viewMalla.setObjectName(_fromUtf8("viewMalla"))
        self.gridLayout_27.addWidget(self.viewMalla, 3, 0, 3, 2)
        self.pbAniadirMallaMod = QtGui.QPushButton(self.formularioMallaMod)
        self.pbAniadirMallaMod.setObjectName(_fromUtf8("pbAniadirMallaMod"))
        self.gridLayout_27.addWidget(self.pbAniadirMallaMod, 3, 2, 1, 1)
        self.pbEditarMallaMod = QtGui.QPushButton(self.formularioMallaMod)
        self.pbEditarMallaMod.setObjectName(_fromUtf8("pbEditarMallaMod"))
        self.gridLayout_27.addWidget(self.pbEditarMallaMod, 4, 2, 1, 1)
        self.pbBorrarMallaMod = QtGui.QPushButton(self.formularioMallaMod)
        self.pbBorrarMallaMod.setObjectName(_fromUtf8("pbBorrarMallaMod"))
        self.gridLayout_27.addWidget(self.pbBorrarMallaMod, 5, 2, 1, 1)
        self.gridLayout_25.addWidget(self.formularioMallaMod, 0, 0, 1, 2)
        self.tabModCarSec.addTab(self.tabMallas_2, _fromUtf8(""))
        self.tabAdhesivoLaminacion_2 = QtGui.QWidget()
        self.tabAdhesivoLaminacion_2.setObjectName(_fromUtf8("tabAdhesivoLaminacion_2"))
        self.gridLayout_28 = QtGui.QGridLayout(self.tabAdhesivoLaminacion_2)
        self.gridLayout_28.setObjectName(_fromUtf8("gridLayout_28"))
        self.formularioAdhLam_2 = QtGui.QFrame(self.tabAdhesivoLaminacion_2)
        self.formularioAdhLam_2.setFrameShape(QtGui.QFrame.StyledPanel)
        self.formularioAdhLam_2.setFrameShadow(QtGui.QFrame.Raised)
        self.formularioAdhLam_2.setObjectName(_fromUtf8("formularioAdhLam_2"))
        self.gridLayout_29 = QtGui.QGridLayout(self.formularioAdhLam_2)
        self.gridLayout_29.setObjectName(_fromUtf8("gridLayout_29"))
        self.lblProveedorAdhLam_2 = QtGui.QLabel(self.formularioAdhLam_2)
        self.lblProveedorAdhLam_2.setObjectName(_fromUtf8("lblProveedorAdhLam_2"))
        self.gridLayout_29.addWidget(self.lblProveedorAdhLam_2, 0, 0, 1, 1)
        self.leProveedorAdhLamMod = QtGui.QLineEdit(self.formularioAdhLam_2)
        self.leProveedorAdhLamMod.setObjectName(_fromUtf8("leProveedorAdhLamMod"))
        self.gridLayout_29.addWidget(self.leProveedorAdhLamMod, 0, 1, 1, 1)
        self.lblAniloxAdhLam_2 = QtGui.QLabel(self.formularioAdhLam_2)
        self.lblAniloxAdhLam_2.setObjectName(_fromUtf8("lblAniloxAdhLam_2"))
        self.gridLayout_29.addWidget(self.lblAniloxAdhLam_2, 1, 0, 1, 1)
        self.leAniloxAdhLamMod = QtGui.QLineEdit(self.formularioAdhLam_2)
        self.leAniloxAdhLamMod.setObjectName(_fromUtf8("leAniloxAdhLamMod"))
        self.gridLayout_29.addWidget(self.leAniloxAdhLamMod, 1, 1, 1, 1)
        self.viewAdhLam = QtGui.QTableView(self.formularioAdhLam_2)
        self.viewAdhLam.setObjectName(_fromUtf8("viewAdhLam"))
        self.gridLayout_29.addWidget(self.viewAdhLam, 2, 0, 3, 2)
        self.pbAniadirAdhLamMod = QtGui.QPushButton(self.formularioAdhLam_2)
        self.pbAniadirAdhLamMod.setObjectName(_fromUtf8("pbAniadirAdhLamMod"))
        self.gridLayout_29.addWidget(self.pbAniadirAdhLamMod, 2, 2, 1, 1)
        self.pbEditarAdhLamMod = QtGui.QPushButton(self.formularioAdhLam_2)
        self.pbEditarAdhLamMod.setObjectName(_fromUtf8("pbEditarAdhLamMod"))
        self.gridLayout_29.addWidget(self.pbEditarAdhLamMod, 3, 2, 1, 1)
        self.pbBorrarAdhLamMod = QtGui.QPushButton(self.formularioAdhLam_2)
        self.pbBorrarAdhLamMod.setObjectName(_fromUtf8("pbBorrarAdhLamMod"))
        self.gridLayout_29.addWidget(self.pbBorrarAdhLamMod, 4, 2, 1, 1)
        self.gridLayout_28.addWidget(self.formularioAdhLam_2, 0, 0, 1, 3)
        self.tabModCarSec.addTab(self.tabAdhesivoLaminacion_2, _fromUtf8(""))
        self.tabAdhesivoColdFoil_2 = QtGui.QWidget()
        self.tabAdhesivoColdFoil_2.setObjectName(_fromUtf8("tabAdhesivoColdFoil_2"))
        self.gridLayout_6 = QtGui.QGridLayout(self.tabAdhesivoColdFoil_2)
        self.gridLayout_6.setObjectName(_fromUtf8("gridLayout_6"))
        self.formularioAdhCoFo_2 = QtGui.QFrame(self.tabAdhesivoColdFoil_2)
        self.formularioAdhCoFo_2.setFrameShape(QtGui.QFrame.StyledPanel)
        self.formularioAdhCoFo_2.setFrameShadow(QtGui.QFrame.Raised)
        self.formularioAdhCoFo_2.setObjectName(_fromUtf8("formularioAdhCoFo_2"))
        self.gridLayout_4 = QtGui.QGridLayout(self.formularioAdhCoFo_2)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.lblProveedorAdhCoFo_2 = QtGui.QLabel(self.formularioAdhCoFo_2)
        self.lblProveedorAdhCoFo_2.setObjectName(_fromUtf8("lblProveedorAdhCoFo_2"))
        self.gridLayout_4.addWidget(self.lblProveedorAdhCoFo_2, 0, 0, 1, 1)
        self.leProveedorAdhCoFoMod = QtGui.QLineEdit(self.formularioAdhCoFo_2)
        self.leProveedorAdhCoFoMod.setObjectName(_fromUtf8("leProveedorAdhCoFoMod"))
        self.gridLayout_4.addWidget(self.leProveedorAdhCoFoMod, 0, 1, 1, 1)
        self.lblAnchoAdhCoFo_2 = QtGui.QLabel(self.formularioAdhCoFo_2)
        self.lblAnchoAdhCoFo_2.setObjectName(_fromUtf8("lblAnchoAdhCoFo_2"))
        self.gridLayout_4.addWidget(self.lblAnchoAdhCoFo_2, 1, 0, 1, 1)
        self.leAniloxAdhCoFoMod = QtGui.QLineEdit(self.formularioAdhCoFo_2)
        self.leAniloxAdhCoFoMod.setObjectName(_fromUtf8("leAniloxAdhCoFoMod"))
        self.gridLayout_4.addWidget(self.leAniloxAdhCoFoMod, 1, 1, 1, 1)
        self.viewAdhCofo = QtGui.QTableView(self.formularioAdhCoFo_2)
        self.viewAdhCofo.setObjectName(_fromUtf8("viewAdhCofo"))
        self.gridLayout_4.addWidget(self.viewAdhCofo, 2, 0, 3, 2)
        self.pbAniadirAdhCoFoMod = QtGui.QPushButton(self.formularioAdhCoFo_2)
        self.pbAniadirAdhCoFoMod.setObjectName(_fromUtf8("pbAniadirAdhCoFoMod"))
        self.gridLayout_4.addWidget(self.pbAniadirAdhCoFoMod, 2, 2, 1, 1)
        self.pbEditarAdhCoFoMod = QtGui.QPushButton(self.formularioAdhCoFo_2)
        self.pbEditarAdhCoFoMod.setObjectName(_fromUtf8("pbEditarAdhCoFoMod"))
        self.gridLayout_4.addWidget(self.pbEditarAdhCoFoMod, 3, 2, 1, 1)
        self.pbBorrarAdhCoFoMod = QtGui.QPushButton(self.formularioAdhCoFo_2)
        self.pbBorrarAdhCoFoMod.setObjectName(_fromUtf8("pbBorrarAdhCoFoMod"))
        self.gridLayout_4.addWidget(self.pbBorrarAdhCoFoMod, 4, 2, 1, 1)
        self.gridLayout_6.addWidget(self.formularioAdhCoFo_2, 0, 1, 1, 1)
        self.tabModCarSec.addTab(self.tabAdhesivoColdFoil_2, _fromUtf8(""))
        self.tabFilmMicronaje_2 = QtGui.QWidget()
        self.tabFilmMicronaje_2.setObjectName(_fromUtf8("tabFilmMicronaje_2"))
        self.gridLayout_32 = QtGui.QGridLayout(self.tabFilmMicronaje_2)
        self.gridLayout_32.setObjectName(_fromUtf8("gridLayout_32"))
        self.formulariFilmMi_2 = QtGui.QFrame(self.tabFilmMicronaje_2)
        self.formulariFilmMi_2.setFrameShape(QtGui.QFrame.StyledPanel)
        self.formulariFilmMi_2.setFrameShadow(QtGui.QFrame.Raised)
        self.formulariFilmMi_2.setObjectName(_fromUtf8("formulariFilmMi_2"))
        self.gridLayout_33 = QtGui.QGridLayout(self.formulariFilmMi_2)
        self.gridLayout_33.setObjectName(_fromUtf8("gridLayout_33"))
        self.lblProveedorFilmMi_2 = QtGui.QLabel(self.formulariFilmMi_2)
        self.lblProveedorFilmMi_2.setObjectName(_fromUtf8("lblProveedorFilmMi_2"))
        self.gridLayout_33.addWidget(self.lblProveedorFilmMi_2, 0, 0, 1, 1)
        self.leProveedorFilmMiMod = QtGui.QLineEdit(self.formulariFilmMi_2)
        self.leProveedorFilmMiMod.setObjectName(_fromUtf8("leProveedorFilmMiMod"))
        self.gridLayout_33.addWidget(self.leProveedorFilmMiMod, 0, 1, 1, 1)
        self.lblAnchoFilmMi_2 = QtGui.QLabel(self.formulariFilmMi_2)
        self.lblAnchoFilmMi_2.setObjectName(_fromUtf8("lblAnchoFilmMi_2"))
        self.gridLayout_33.addWidget(self.lblAnchoFilmMi_2, 1, 0, 1, 1)
        self.dsbAnchoFilmMiMod = QtGui.QDoubleSpinBox(self.formulariFilmMi_2)
        self.dsbAnchoFilmMiMod.setDecimals(2)
        self.dsbAnchoFilmMiMod.setObjectName(_fromUtf8("dsbAnchoFilmMiMod"))
        self.gridLayout_33.addWidget(self.dsbAnchoFilmMiMod, 1, 1, 1, 1)
        self.viewFilmmi = QtGui.QTableView(self.formulariFilmMi_2)
        self.viewFilmmi.setObjectName(_fromUtf8("viewFilmmi"))
        self.gridLayout_33.addWidget(self.viewFilmmi, 2, 0, 3, 2)
        self.pbAniadirFilmMiMod = QtGui.QPushButton(self.formulariFilmMi_2)
        self.pbAniadirFilmMiMod.setObjectName(_fromUtf8("pbAniadirFilmMiMod"))
        self.gridLayout_33.addWidget(self.pbAniadirFilmMiMod, 2, 2, 1, 1)
        self.pbEditarFilmMiMod = QtGui.QPushButton(self.formulariFilmMi_2)
        self.pbEditarFilmMiMod.setObjectName(_fromUtf8("pbEditarFilmMiMod"))
        self.gridLayout_33.addWidget(self.pbEditarFilmMiMod, 3, 2, 1, 1)
        self.pbBorrarFilmMiMod = QtGui.QPushButton(self.formulariFilmMi_2)
        self.pbBorrarFilmMiMod.setObjectName(_fromUtf8("pbBorrarFilmMiMod"))
        self.gridLayout_33.addWidget(self.pbBorrarFilmMiMod, 4, 2, 1, 1)
        self.gridLayout_32.addWidget(self.formulariFilmMi_2, 0, 0, 1, 2)
        self.tabModCarSec.addTab(self.tabFilmMicronaje_2, _fromUtf8(""))
        self.tabColdFoil_2 = QtGui.QWidget()
        self.tabColdFoil_2.setObjectName(_fromUtf8("tabColdFoil_2"))
        self.gridLayout_34 = QtGui.QGridLayout(self.tabColdFoil_2)
        self.gridLayout_34.setObjectName(_fromUtf8("gridLayout_34"))
        self.formularioColdFoil_2 = QtGui.QFrame(self.tabColdFoil_2)
        self.formularioColdFoil_2.setFrameShape(QtGui.QFrame.StyledPanel)
        self.formularioColdFoil_2.setFrameShadow(QtGui.QFrame.Raised)
        self.formularioColdFoil_2.setObjectName(_fromUtf8("formularioColdFoil_2"))
        self.gridLayout_7 = QtGui.QGridLayout(self.formularioColdFoil_2)
        self.gridLayout_7.setObjectName(_fromUtf8("gridLayout_7"))
        self.rbCF = QtGui.QRadioButton(self.formularioColdFoil_2)
        self.rbCF.setChecked(True)
        self.rbCF.setObjectName(_fromUtf8("rbCF"))
        self.gridLayout_7.addWidget(self.rbCF, 0, 0, 1, 2)
        self.rbHS = QtGui.QRadioButton(self.formularioColdFoil_2)
        self.rbHS.setObjectName(_fromUtf8("rbHS"))
        self.gridLayout_7.addWidget(self.rbHS, 0, 2, 1, 1)
        spacerItem1 = QtGui.QSpacerItem(320, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_7.addItem(spacerItem1, 0, 3, 1, 1)
        self.lblProveedorColdFoil_2 = QtGui.QLabel(self.formularioColdFoil_2)
        self.lblProveedorColdFoil_2.setObjectName(_fromUtf8("lblProveedorColdFoil_2"))
        self.gridLayout_7.addWidget(self.lblProveedorColdFoil_2, 1, 0, 1, 1)
        self.leProveedorColdFoilMod = QtGui.QLineEdit(self.formularioColdFoil_2)
        self.leProveedorColdFoilMod.setObjectName(_fromUtf8("leProveedorColdFoilMod"))
        self.gridLayout_7.addWidget(self.leProveedorColdFoilMod, 1, 1, 1, 3)
        self.lblAnchoColdFoil_2 = QtGui.QLabel(self.formularioColdFoil_2)
        self.lblAnchoColdFoil_2.setObjectName(_fromUtf8("lblAnchoColdFoil_2"))
        self.gridLayout_7.addWidget(self.lblAnchoColdFoil_2, 2, 0, 1, 1)
        self.dsbAnchoColdFoilMod = QtGui.QDoubleSpinBox(self.formularioColdFoil_2)
        self.dsbAnchoColdFoilMod.setDecimals(2)
        self.dsbAnchoColdFoilMod.setObjectName(_fromUtf8("dsbAnchoColdFoilMod"))
        self.gridLayout_7.addWidget(self.dsbAnchoColdFoilMod, 2, 1, 1, 2)
        self.viewColdFoil = QtGui.QTableView(self.formularioColdFoil_2)
        self.viewColdFoil.setObjectName(_fromUtf8("viewColdFoil"))
        self.gridLayout_7.addWidget(self.viewColdFoil, 3, 0, 3, 4)
        self.pbAniadirColdFoilMod = QtGui.QPushButton(self.formularioColdFoil_2)
        self.pbAniadirColdFoilMod.setObjectName(_fromUtf8("pbAniadirColdFoilMod"))
        self.gridLayout_7.addWidget(self.pbAniadirColdFoilMod, 3, 4, 1, 1)
        self.pbEditarColdFoilMod = QtGui.QPushButton(self.formularioColdFoil_2)
        self.pbEditarColdFoilMod.setObjectName(_fromUtf8("pbEditarColdFoilMod"))
        self.gridLayout_7.addWidget(self.pbEditarColdFoilMod, 4, 4, 1, 1)
        self.pbBorrarColdFoilMod = QtGui.QPushButton(self.formularioColdFoil_2)
        self.pbBorrarColdFoilMod.setObjectName(_fromUtf8("pbBorrarColdFoilMod"))
        self.gridLayout_7.addWidget(self.pbBorrarColdFoilMod, 5, 4, 1, 1)
        self.gridLayout_34.addWidget(self.formularioColdFoil_2, 0, 0, 1, 2)
        self.tabModCarSec.addTab(self.tabColdFoil_2, _fromUtf8(""))
        self.tabTipoBarniz_2 = QtGui.QWidget()
        self.tabTipoBarniz_2.setObjectName(_fromUtf8("tabTipoBarniz_2"))
        self.gridLayout_36 = QtGui.QGridLayout(self.tabTipoBarniz_2)
        self.gridLayout_36.setObjectName(_fromUtf8("gridLayout_36"))
        self.frame_3 = QtGui.QFrame(self.tabTipoBarniz_2)
        self.frame_3.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_3.setObjectName(_fromUtf8("frame_3"))
        self.gridLayout_37 = QtGui.QGridLayout(self.frame_3)
        self.gridLayout_37.setObjectName(_fromUtf8("gridLayout_37"))
        self.lblTipoTBarniz_2 = QtGui.QLabel(self.frame_3)
        self.lblTipoTBarniz_2.setObjectName(_fromUtf8("lblTipoTBarniz_2"))
        self.gridLayout_37.addWidget(self.lblTipoTBarniz_2, 0, 0, 1, 1)
        self.leTipoTBarnizMod = QtGui.QLineEdit(self.frame_3)
        self.leTipoTBarnizMod.setObjectName(_fromUtf8("leTipoTBarnizMod"))
        self.gridLayout_37.addWidget(self.leTipoTBarnizMod, 0, 1, 1, 1)
        self.lblProveedorTBarniz_2 = QtGui.QLabel(self.frame_3)
        self.lblProveedorTBarniz_2.setObjectName(_fromUtf8("lblProveedorTBarniz_2"))
        self.gridLayout_37.addWidget(self.lblProveedorTBarniz_2, 1, 0, 1, 1)
        self.leProveedorTBarnizMod = QtGui.QLineEdit(self.frame_3)
        self.leProveedorTBarnizMod.setObjectName(_fromUtf8("leProveedorTBarnizMod"))
        self.gridLayout_37.addWidget(self.leProveedorTBarnizMod, 1, 1, 1, 1)
        self.lblAniloxTBarniz_2 = QtGui.QLabel(self.frame_3)
        self.lblAniloxTBarniz_2.setObjectName(_fromUtf8("lblAniloxTBarniz_2"))
        self.gridLayout_37.addWidget(self.lblAniloxTBarniz_2, 2, 0, 1, 1)
        self.leAniloxTBarnizMod = QtGui.QLineEdit(self.frame_3)
        self.leAniloxTBarnizMod.setObjectName(_fromUtf8("leAniloxTBarnizMod"))
        self.gridLayout_37.addWidget(self.leAniloxTBarnizMod, 2, 1, 1, 1)
        self.pbEditarTBarnizMod = QtGui.QPushButton(self.frame_3)
        self.pbEditarTBarnizMod.setObjectName(_fromUtf8("pbEditarTBarnizMod"))
        self.gridLayout_37.addWidget(self.pbEditarTBarnizMod, 5, 3, 1, 1)
        self.pbBorrarTBarnizMod = QtGui.QPushButton(self.frame_3)
        self.pbBorrarTBarnizMod.setObjectName(_fromUtf8("pbBorrarTBarnizMod"))
        self.gridLayout_37.addWidget(self.pbBorrarTBarnizMod, 6, 3, 1, 1)
        self.pbAniadirTBarnizMod = QtGui.QPushButton(self.frame_3)
        self.pbAniadirTBarnizMod.setObjectName(_fromUtf8("pbAniadirTBarnizMod"))
        self.gridLayout_37.addWidget(self.pbAniadirTBarnizMod, 4, 3, 1, 1)
        self.viewTipoBarniz = QtGui.QTableView(self.frame_3)
        self.viewTipoBarniz.setObjectName(_fromUtf8("viewTipoBarniz"))
        self.gridLayout_37.addWidget(self.viewTipoBarniz, 4, 0, 3, 2)
        self.gridLayout_36.addWidget(self.frame_3, 0, 0, 1, 2)
        self.tabModCarSec.addTab(self.tabTipoBarniz_2, _fromUtf8(""))
        self.tabTroquel_2 = QtGui.QWidget()
        self.tabTroquel_2.setObjectName(_fromUtf8("tabTroquel_2"))
        self.gridLayout_38 = QtGui.QGridLayout(self.tabTroquel_2)
        self.gridLayout_38.setObjectName(_fromUtf8("gridLayout_38"))
        self.frame_4 = QtGui.QFrame(self.tabTroquel_2)
        self.frame_4.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_4.setObjectName(_fromUtf8("frame_4"))
        self.gridLayout_5 = QtGui.QGridLayout(self.frame_4)
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        self.lblProveedorTroquel_2 = QtGui.QLabel(self.frame_4)
        self.lblProveedorTroquel_2.setObjectName(_fromUtf8("lblProveedorTroquel_2"))
        self.gridLayout_5.addWidget(self.lblProveedorTroquel_2, 0, 0, 1, 1)
        self.leProveedorTroquelMod = QtGui.QLineEdit(self.frame_4)
        self.leProveedorTroquelMod.setObjectName(_fromUtf8("leProveedorTroquelMod"))
        self.gridLayout_5.addWidget(self.leProveedorTroquelMod, 0, 1, 1, 1)
        self.lblObservaciones = QtGui.QLabel(self.frame_4)
        self.lblObservaciones.setObjectName(_fromUtf8("lblObservaciones"))
        self.gridLayout_5.addWidget(self.lblObservaciones, 1, 0, 1, 1)
        self.leObservacionesTroquelMod = QtGui.QLineEdit(self.frame_4)
        self.leObservacionesTroquelMod.setObjectName(_fromUtf8("leObservacionesTroquelMod"))
        self.gridLayout_5.addWidget(self.leObservacionesTroquelMod, 1, 1, 1, 1)
        self.viewTroquel = QtGui.QTableView(self.frame_4)
        self.viewTroquel.setObjectName(_fromUtf8("viewTroquel"))
        self.gridLayout_5.addWidget(self.viewTroquel, 2, 0, 3, 2)
        self.pbAniadirTroquelMod = QtGui.QPushButton(self.frame_4)
        self.pbAniadirTroquelMod.setObjectName(_fromUtf8("pbAniadirTroquelMod"))
        self.gridLayout_5.addWidget(self.pbAniadirTroquelMod, 2, 2, 1, 1)
        self.pbEditarTroquelMod = QtGui.QPushButton(self.frame_4)
        self.pbEditarTroquelMod.setObjectName(_fromUtf8("pbEditarTroquelMod"))
        self.gridLayout_5.addWidget(self.pbEditarTroquelMod, 3, 2, 1, 1)
        self.pbBorrarTroquelMod = QtGui.QPushButton(self.frame_4)
        self.pbBorrarTroquelMod.setObjectName(_fromUtf8("pbBorrarTroquelMod"))
        self.gridLayout_5.addWidget(self.pbBorrarTroquelMod, 4, 2, 1, 1)
        self.gridLayout_38.addWidget(self.frame_4, 0, 0, 1, 2)
        self.tabModCarSec.addTab(self.tabTroquel_2, _fromUtf8(""))
        self.verticalLayout_13.addWidget(self.tabModCarSec)
        self.tabModificarFicha.addTab(self.tabCaracteristicas_2, _fromUtf8(""))
        self.verticalLayout_14.addWidget(self.tabModificarFicha)
        self.verticalLayout_12.addWidget(self.groupBox_2)
        self.pbModificarFicha = QtGui.QPushButton(self.tabModificarficha)
        self.pbModificarFicha.setObjectName(_fromUtf8("pbModificarFicha"))
        self.verticalLayout_12.addWidget(self.pbModificarFicha)
        self.tabOpFichas.addTab(self.tabModificarficha, _fromUtf8(""))
        self.tabConsultarFicha = QtGui.QWidget()
        self.tabConsultarFicha.setObjectName(_fromUtf8("tabConsultarFicha"))
        self.verticalLayout_9 = QtGui.QVBoxLayout(self.tabConsultarFicha)
        self.verticalLayout_9.setObjectName(_fromUtf8("verticalLayout_9"))
        self.scrollArea = QtGui.QScrollArea(self.tabConsultarFicha)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName(_fromUtf8("scrollArea"))
        self.scrollAreaWidgetContents = QtGui.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 659, 459))
        self.scrollAreaWidgetContents.setObjectName(_fromUtf8("scrollAreaWidgetContents"))
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.verticalLayout_6 = QtGui.QVBoxLayout()
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.groupBox = QtGui.QGroupBox(self.scrollAreaWidgetContents)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.groupBox)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.verticalLayout_7 = QtGui.QVBoxLayout()
        self.verticalLayout_7.setObjectName(_fromUtf8("verticalLayout_7"))
        self.rbCategoria = QtGui.QRadioButton(self.groupBox)
        self.rbCategoria.setObjectName(_fromUtf8("rbCategoria"))
        self.verticalLayout_7.addWidget(self.rbCategoria)
        self.rbPedidos = QtGui.QRadioButton(self.groupBox)
        self.rbPedidos.setObjectName(_fromUtf8("rbPedidos"))
        self.verticalLayout_7.addWidget(self.rbPedidos)
        self.rbEtiqueta = QtGui.QRadioButton(self.groupBox)
        self.rbEtiqueta.setObjectName(_fromUtf8("rbEtiqueta"))
        self.verticalLayout_7.addWidget(self.rbEtiqueta)
        self.rbCliente = QtGui.QRadioButton(self.groupBox)
        self.rbCliente.setObjectName(_fromUtf8("rbCliente"))
        self.verticalLayout_7.addWidget(self.rbCliente)
        self.verticalLayout_3.addLayout(self.verticalLayout_7)
        self.horizontalLayout.addWidget(self.groupBox)
        self.verticalLayout_8 = QtGui.QVBoxLayout()
        self.verticalLayout_8.setObjectName(_fromUtf8("verticalLayout_8"))
        self.cmbBusqueda = QtGui.QComboBox(self.scrollAreaWidgetContents)
        self.cmbBusqueda.setObjectName(_fromUtf8("cmbBusqueda"))
        self.verticalLayout_8.addWidget(self.cmbBusqueda)
        self.horizontalLayout.addLayout(self.verticalLayout_8)
        self.verticalLayout_6.addLayout(self.horizontalLayout)
        self.twFichas = QtGui.QTableWidget(self.scrollAreaWidgetContents)
        self.twFichas.setObjectName(_fromUtf8("twFichas"))
        self.twFichas.setColumnCount(0)
        self.twFichas.setRowCount(0)
        self.verticalLayout_6.addWidget(self.twFichas)
        self.pbMostrarFicha = QtGui.QPushButton(self.scrollAreaWidgetContents)
        self.pbMostrarFicha.setObjectName(_fromUtf8("pbMostrarFicha"))
        self.verticalLayout_6.addWidget(self.pbMostrarFicha)
        self.verticalLayout_5.addLayout(self.verticalLayout_6)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout_9.addWidget(self.scrollArea)
        self.tabOpFichas.addTab(self.tabConsultarFicha, _fromUtf8(""))
        self.verticalLayout_4.addWidget(self.tabOpFichas)
        self.tabPrincipal.addTab(self.tabAdministrarFichas, _fromUtf8(""))
        self.tabAdministrarCategorias = QtGui.QWidget()
        self.tabAdministrarCategorias.setObjectName(_fromUtf8("tabAdministrarCategorias"))
        self.gridLayout_14 = QtGui.QGridLayout(self.tabAdministrarCategorias)
        self.gridLayout_14.setObjectName(_fromUtf8("gridLayout_14"))
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.verticalLayout_10 = QtGui.QVBoxLayout()
        self.verticalLayout_10.setObjectName(_fromUtf8("verticalLayout_10"))
        self.pbAniadirCategoria = QtGui.QPushButton(self.tabAdministrarCategorias)
        self.pbAniadirCategoria.setObjectName(_fromUtf8("pbAniadirCategoria"))
        self.verticalLayout_10.addWidget(self.pbAniadirCategoria)
        self.pbEditarCategoria = QtGui.QPushButton(self.tabAdministrarCategorias)
        self.pbEditarCategoria.setObjectName(_fromUtf8("pbEditarCategoria"))
        self.verticalLayout_10.addWidget(self.pbEditarCategoria)
        self.horizontalLayout_4.addLayout(self.verticalLayout_10)
        self.twCatergoria = QtGui.QTableWidget(self.tabAdministrarCategorias)
        self.twCatergoria.setObjectName(_fromUtf8("twCatergoria"))
        self.twCatergoria.setColumnCount(1)
        self.twCatergoria.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.twCatergoria.setHorizontalHeaderItem(0, item)
        self.horizontalLayout_4.addWidget(self.twCatergoria)
        self.gridLayout_14.addLayout(self.horizontalLayout_4, 0, 0, 2, 2)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_14.addItem(spacerItem2, 0, 2, 1, 1)
        spacerItem3 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_14.addItem(spacerItem3, 2, 0, 1, 1)
        self.tabPrincipal.addTab(self.tabAdministrarCategorias, _fromUtf8(""))
        self.tabAdministraClientes = QtGui.QWidget()
        self.tabAdministraClientes.setObjectName(_fromUtf8("tabAdministraClientes"))
        self.gridLayout_8 = QtGui.QGridLayout(self.tabAdministraClientes)
        self.gridLayout_8.setObjectName(_fromUtf8("gridLayout_8"))
        self.lblRut = QtGui.QLabel(self.tabAdministraClientes)
        self.lblRut.setObjectName(_fromUtf8("lblRut"))
        self.gridLayout_8.addWidget(self.lblRut, 0, 0, 1, 1)
        self.leRutCliente = QtGui.QLineEdit(self.tabAdministraClientes)
        self.leRutCliente.setObjectName(_fromUtf8("leRutCliente"))
        self.gridLayout_8.addWidget(self.leRutCliente, 0, 1, 1, 1)
        self.lblNombre = QtGui.QLabel(self.tabAdministraClientes)
        self.lblNombre.setObjectName(_fromUtf8("lblNombre"))
        self.gridLayout_8.addWidget(self.lblNombre, 1, 0, 1, 1)
        self.leNombreCliente = QtGui.QLineEdit(self.tabAdministraClientes)
        self.leNombreCliente.setObjectName(_fromUtf8("leNombreCliente"))
        self.gridLayout_8.addWidget(self.leNombreCliente, 1, 1, 1, 1)
        self.pbAniadirCliente = QtGui.QPushButton(self.tabAdministraClientes)
        self.pbAniadirCliente.setObjectName(_fromUtf8("pbAniadirCliente"))
        self.gridLayout_8.addWidget(self.pbAniadirCliente, 2, 0, 1, 1)
        self.twCliente = QtGui.QTableWidget(self.tabAdministraClientes)
        self.twCliente.setObjectName(_fromUtf8("twCliente"))
        self.twCliente.setColumnCount(2)
        self.twCliente.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.twCliente.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.twCliente.setHorizontalHeaderItem(1, item)
        self.gridLayout_8.addWidget(self.twCliente, 2, 1, 3, 1)
        self.pbEditarCliente = QtGui.QPushButton(self.tabAdministraClientes)
        self.pbEditarCliente.setObjectName(_fromUtf8("pbEditarCliente"))
        self.gridLayout_8.addWidget(self.pbEditarCliente, 3, 0, 1, 1)
        self.tabPrincipal.addTab(self.tabAdministraClientes, _fromUtf8(""))
        self.tabAdministrarMaquinas = QtGui.QWidget()
        self.tabAdministrarMaquinas.setObjectName(_fromUtf8("tabAdministrarMaquinas"))
        self.gridLayout_9 = QtGui.QGridLayout(self.tabAdministrarMaquinas)
        self.gridLayout_9.setObjectName(_fromUtf8("gridLayout_9"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.pbAniadirMaquina = QtGui.QPushButton(self.tabAdministrarMaquinas)
        self.pbAniadirMaquina.setObjectName(_fromUtf8("pbAniadirMaquina"))
        self.verticalLayout.addWidget(self.pbAniadirMaquina)
        self.pbEditarMaquina = QtGui.QPushButton(self.tabAdministrarMaquinas)
        self.pbEditarMaquina.setObjectName(_fromUtf8("pbEditarMaquina"))
        self.verticalLayout.addWidget(self.pbEditarMaquina)
        self.horizontalLayout_3.addLayout(self.verticalLayout)
        self.twMaquina = QtGui.QTableWidget(self.tabAdministrarMaquinas)
        self.twMaquina.setObjectName(_fromUtf8("twMaquina"))
        self.twMaquina.setColumnCount(1)
        self.twMaquina.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.twMaquina.setHorizontalHeaderItem(0, item)
        self.horizontalLayout_3.addWidget(self.twMaquina)
        self.gridLayout_9.addLayout(self.horizontalLayout_3, 0, 0, 1, 1)
        spacerItem4 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_9.addItem(spacerItem4, 2, 0, 1, 1)
        spacerItem5 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_9.addItem(spacerItem5, 0, 1, 1, 1)
        self.tabPrincipal.addTab(self.tabAdministrarMaquinas, _fromUtf8(""))
        self.gridLayout_2.addWidget(self.tabPrincipal, 0, 0, 1, 1)

        self.retranslateUi(Dialog)
        self.tabPrincipal.setCurrentIndex(0)
        self.tabOpFichas.setCurrentIndex(1)
        self.tabModificarFicha.setCurrentIndex(3)
        self.tabModCarSec.setCurrentIndex(4)
        QtCore.QMetaObject.connectSlotsByName(Dialog)
        Dialog.setTabOrder(self.tabOpFichas, self.cmbCategoria)
        Dialog.setTabOrder(self.cmbCategoria, self.cmbCliente)
        Dialog.setTabOrder(self.cmbCliente, self.cmbMaquina)
        Dialog.setTabOrder(self.cmbMaquina, self.lePedido)
        Dialog.setTabOrder(self.lePedido, self.leEtiqueta)
        Dialog.setTabOrder(self.leEtiqueta, self.deFechaFicha)
        Dialog.setTabOrder(self.deFechaFicha, self.dsbVelocidadFicha)
        Dialog.setTabOrder(self.dsbVelocidadFicha, self.rbConvencionales)
        Dialog.setTabOrder(self.rbConvencionales, self.rbDigitales)
        Dialog.setTabOrder(self.rbDigitales, self.pbGuardarFicha)
        Dialog.setTabOrder(self.pbGuardarFicha, self.cmbModificar)
        Dialog.setTabOrder(self.cmbModificar, self.rbModificarEtiqueta)
        Dialog.setTabOrder(self.rbModificarEtiqueta, self.rbModificarPorPedido)
        Dialog.setTabOrder(self.rbModificarPorPedido, self.tabModificarFicha)
        Dialog.setTabOrder(self.tabModificarFicha, self.cmbCategoriaMod)
        Dialog.setTabOrder(self.cmbCategoriaMod, self.cmbClienteMod)
        Dialog.setTabOrder(self.cmbClienteMod, self.cmbMaquinaMod)
        Dialog.setTabOrder(self.cmbMaquinaMod, self.lePedidoMod)
        Dialog.setTabOrder(self.lePedidoMod, self.leEtiquetaMod)
        Dialog.setTabOrder(self.leEtiquetaMod, self.deFechaFichaMod)
        Dialog.setTabOrder(self.deFechaFichaMod, self.dsbVelocidadFichaMod)
        Dialog.setTabOrder(self.dsbVelocidadFichaMod, self.rbConvencionalesMod)
        Dialog.setTabOrder(self.rbConvencionalesMod, self.rbDigitalesMod)
        Dialog.setTabOrder(self.rbDigitalesMod, self.leCodigoMaterialMod)
        Dialog.setTabOrder(self.leCodigoMaterialMod, self.leNombreMaterialMod)
        Dialog.setTabOrder(self.leNombreMaterialMod, self.leProveedorMaterialMod)
        Dialog.setTabOrder(self.leProveedorMaterialMod, self.dsbAnchoMaterialMod)
        Dialog.setTabOrder(self.dsbAnchoMaterialMod, self.rbTC1Mod)
        Dialog.setTabOrder(self.rbTC1Mod, self.rbTC2Mod)
        Dialog.setTabOrder(self.rbTC2Mod, self.pbAniadirMaterialMod)
        Dialog.setTabOrder(self.pbAniadirMaterialMod, self.pbEditarMaterialMod)
        Dialog.setTabOrder(self.pbEditarMaterialMod, self.pbBorrarMaterialMod)
        Dialog.setTabOrder(self.pbBorrarMaterialMod, self.viewMateriales)
        Dialog.setTabOrder(self.viewMateriales, self.leColorTintaMod)
        Dialog.setTabOrder(self.leColorTintaMod, self.leTipoTintaMod)
        Dialog.setTabOrder(self.leTipoTintaMod, self.leAniloxTintaMod)
        Dialog.setTabOrder(self.leAniloxTintaMod, self.leProveedorTintaMod)
        Dialog.setTabOrder(self.leProveedorTintaMod, self.leProveedorTinta2Mod)
        Dialog.setTabOrder(self.leProveedorTinta2Mod, self.leProveedorTinta3Mod)
        Dialog.setTabOrder(self.leProveedorTinta3Mod, self.pbAniadirTintaMod)
        Dialog.setTabOrder(self.pbAniadirTintaMod, self.pbEditarTintaMod)
        Dialog.setTabOrder(self.pbEditarTintaMod, self.pbBorrarTintaMod)
        Dialog.setTabOrder(self.pbBorrarTintaMod, self.viewTintas)
        Dialog.setTabOrder(self.viewTintas, self.tabPrincipal)
        Dialog.setTabOrder(self.tabPrincipal, self.tabModCarSec)
        Dialog.setTabOrder(self.tabModCarSec, self.leTipoMallaMod)
        Dialog.setTabOrder(self.leTipoMallaMod, self.rbInterno_2)
        Dialog.setTabOrder(self.rbInterno_2, self.rbExternoMod)
        Dialog.setTabOrder(self.rbExternoMod, self.pbAniadirMallaMod)
        Dialog.setTabOrder(self.pbAniadirMallaMod, self.pbEditarMallaMod)
        Dialog.setTabOrder(self.pbEditarMallaMod, self.pbBorrarMallaMod)
        Dialog.setTabOrder(self.pbBorrarMallaMod, self.viewMalla)
        Dialog.setTabOrder(self.viewMalla, self.leProveedorAdhLamMod)
        Dialog.setTabOrder(self.leProveedorAdhLamMod, self.leAniloxAdhLamMod)
        Dialog.setTabOrder(self.leAniloxAdhLamMod, self.pbAniadirAdhLamMod)
        Dialog.setTabOrder(self.pbAniadirAdhLamMod, self.pbEditarAdhLamMod)
        Dialog.setTabOrder(self.pbEditarAdhLamMod, self.pbBorrarAdhLamMod)
        Dialog.setTabOrder(self.pbBorrarAdhLamMod, self.viewAdhLam)
        Dialog.setTabOrder(self.viewAdhLam, self.leProveedorAdhCoFoMod)
        Dialog.setTabOrder(self.leProveedorAdhCoFoMod, self.leAniloxAdhCoFoMod)
        Dialog.setTabOrder(self.leAniloxAdhCoFoMod, self.pbAniadirAdhCoFoMod)
        Dialog.setTabOrder(self.pbAniadirAdhCoFoMod, self.pbEditarAdhCoFoMod)
        Dialog.setTabOrder(self.pbEditarAdhCoFoMod, self.pbBorrarAdhCoFoMod)
        Dialog.setTabOrder(self.pbBorrarAdhCoFoMod, self.viewAdhCofo)
        Dialog.setTabOrder(self.viewAdhCofo, self.leProveedorFilmMiMod)
        Dialog.setTabOrder(self.leProveedorFilmMiMod, self.dsbAnchoFilmMiMod)
        Dialog.setTabOrder(self.dsbAnchoFilmMiMod, self.pbAniadirFilmMiMod)
        Dialog.setTabOrder(self.pbAniadirFilmMiMod, self.pbEditarFilmMiMod)
        Dialog.setTabOrder(self.pbEditarFilmMiMod, self.pbBorrarFilmMiMod)
        Dialog.setTabOrder(self.pbBorrarFilmMiMod, self.viewFilmmi)
        Dialog.setTabOrder(self.viewFilmmi, self.leProveedorColdFoilMod)
        Dialog.setTabOrder(self.leProveedorColdFoilMod, self.dsbAnchoColdFoilMod)
        Dialog.setTabOrder(self.dsbAnchoColdFoilMod, self.pbAniadirColdFoilMod)
        Dialog.setTabOrder(self.pbAniadirColdFoilMod, self.pbEditarColdFoilMod)
        Dialog.setTabOrder(self.pbEditarColdFoilMod, self.pbBorrarColdFoilMod)
        Dialog.setTabOrder(self.pbBorrarColdFoilMod, self.viewColdFoil)
        Dialog.setTabOrder(self.viewColdFoil, self.leTipoTBarnizMod)
        Dialog.setTabOrder(self.leTipoTBarnizMod, self.leProveedorTBarnizMod)
        Dialog.setTabOrder(self.leProveedorTBarnizMod, self.leAniloxTBarnizMod)
        Dialog.setTabOrder(self.leAniloxTBarnizMod, self.pbAniadirTBarnizMod)
        Dialog.setTabOrder(self.pbAniadirTBarnizMod, self.pbEditarTBarnizMod)
        Dialog.setTabOrder(self.pbEditarTBarnizMod, self.pbBorrarTBarnizMod)
        Dialog.setTabOrder(self.pbBorrarTBarnizMod, self.viewTipoBarniz)
        Dialog.setTabOrder(self.viewTipoBarniz, self.leProveedorTroquelMod)
        Dialog.setTabOrder(self.leProveedorTroquelMod, self.leObservacionesTroquelMod)
        Dialog.setTabOrder(self.leObservacionesTroquelMod, self.pbAniadirTroquelMod)
        Dialog.setTabOrder(self.pbAniadirTroquelMod, self.pbEditarTroquelMod)
        Dialog.setTabOrder(self.pbEditarTroquelMod, self.pbBorrarTroquelMod)
        Dialog.setTabOrder(self.pbBorrarTroquelMod, self.viewTroquel)
        Dialog.setTabOrder(self.viewTroquel, self.scrollArea)
        Dialog.setTabOrder(self.scrollArea, self.rbCategoria)
        Dialog.setTabOrder(self.rbCategoria, self.rbPedidos)
        Dialog.setTabOrder(self.rbPedidos, self.rbEtiqueta)
        Dialog.setTabOrder(self.rbEtiqueta, self.rbCliente)
        Dialog.setTabOrder(self.rbCliente, self.cmbBusqueda)
        Dialog.setTabOrder(self.cmbBusqueda, self.twFichas)
        Dialog.setTabOrder(self.twFichas, self.twCatergoria)
        Dialog.setTabOrder(self.twCatergoria, self.pbAniadirCategoria)
        Dialog.setTabOrder(self.pbAniadirCategoria, self.pbEditarCategoria)
        Dialog.setTabOrder(self.pbEditarCategoria, self.leRutCliente)
        Dialog.setTabOrder(self.leRutCliente, self.leNombreCliente)
        Dialog.setTabOrder(self.leNombreCliente, self.twCliente)
        Dialog.setTabOrder(self.twCliente, self.pbAniadirCliente)
        Dialog.setTabOrder(self.pbAniadirCliente, self.pbEditarCliente)
        Dialog.setTabOrder(self.pbEditarCliente, self.twMaquina)
        Dialog.setTabOrder(self.twMaquina, self.pbAniadirMaquina)
        Dialog.setTabOrder(self.pbAniadirMaquina, self.pbEditarMaquina)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(_translate("Dialog", "Dialog", None))
        self.label_3.setText(_translate("Dialog", "Categoria", None))
        self.lblCliente.setText(_translate("Dialog", "Cliente", None))
        self.lblMaquina.setText(_translate("Dialog", "Maquina", None))
        self.lblPedido.setText(_translate("Dialog", "Pedido", None))
        self.lblEtiqueta.setText(_translate("Dialog", "Etiqueta", None))
        self.lblFecha.setText(_translate("Dialog", "Fecha", None))
        self.lblVelocidad_2.setText(_translate("Dialog", " Velocidad de la Maquina(m/m )", None))
        self.lblClisses.setText(_translate("Dialog", "Clisses", None))
        self.rbConvencionales.setText(_translate("Dialog", "Convencionales", None))
        self.rbDigitales.setText(_translate("Dialog", "Digitales", None))
        self.pbGuardarFicha.setText(_translate("Dialog", "Guardar Ficha", None))
        self.tabOpFichas.setTabText(self.tabOpFichas.indexOf(self.tab_4), _translate("Dialog", "Crear Ficha", None))
        self.groupBox_2.setTitle(_translate("Dialog", "Seleccione como desea buscar", None))
        self.cmbModificar.setItemText(0, _translate("Dialog", "Seleccione Filtro", None))
        self.rbModificarEtiqueta.setText(_translate("Dialog", "Etiqueta", None))
        self.rbModificarPorPedido.setText(_translate("Dialog", "Pedido", None))
        self.lblPedido_2.setText(_translate("Dialog", "Pedido", None))
        self.lblEtiqueta_2.setText(_translate("Dialog", "Etiqueta", None))
        self.lblVelocidad_3.setText(_translate("Dialog", " Velocidad de la Maquina(m/m )", None))
        self.lblMaquina_2.setText(_translate("Dialog", "Maquina", None))
        self.lblClisses_2.setText(_translate("Dialog", "Clisses", None))
        self.label_4.setText(_translate("Dialog", "Categoria", None))
        self.rbDigitalesMod.setText(_translate("Dialog", "Digitales", None))
        self.lblCliente_2.setText(_translate("Dialog", "Cliente", None))
        self.lblFecha_2.setText(_translate("Dialog", "Fecha", None))
        self.rbConvencionalesMod.setText(_translate("Dialog", "Convencionales", None))
        self.tabModificarFicha.setTabText(self.tabModificarFicha.indexOf(self.tabFicha_2), _translate("Dialog", "Datos Ficha", None))
        self.lblCodigoMaterial_2.setText(_translate("Dialog", "Codigo", None))
        self.lblNombreMaterial_2.setText(_translate("Dialog", "Nombre", None))
        self.lblProveedorMaterial_2.setText(_translate("Dialog", "Proveedor", None))
        self.lblAncho_2.setText(_translate("Dialog", "Ancho(cm)", None))
        self.lblTC_2.setText(_translate("Dialog", "¿ TC ?", None))
        self.rbTC1Mod.setText(_translate("Dialog", "Si", None))
        self.rbTC2Mod.setText(_translate("Dialog", "No", None))
        self.pbAniadirMaterialMod.setText(_translate("Dialog", "Añadir Material", None))
        self.pbEditarMaterialMod.setText(_translate("Dialog", "Editar Material", None))
        self.pbBorrarMaterialMod.setText(_translate("Dialog", "Borrar Material", None))
        self.tabModificarFicha.setTabText(self.tabModificarFicha.indexOf(self.tabMateriales_2), _translate("Dialog", "Materiales", None))
        self.lblColor_3.setText(_translate("Dialog", "Color", None))
        self.lblTipoTinta_2.setText(_translate("Dialog", "Tipo", None))
        self.lblAniloxTinta_2.setText(_translate("Dialog", "Anilox", None))
        self.lblProveedor_2.setText(_translate("Dialog", "Proveedor ", None))
        self.lblProveedor2_2.setText(_translate("Dialog", "Proveedor 2", None))
        self.lblProveedor3_2.setText(_translate("Dialog", "Proveedor  3", None))
        self.pbAniadirTintaMod.setText(_translate("Dialog", "Añadir Tinta", None))
        self.pbEditarTintaMod.setText(_translate("Dialog", "Editar Tinta", None))
        self.pbBorrarTintaMod.setText(_translate("Dialog", "Borrar Tinta", None))
        self.tabModificarFicha.setTabText(self.tabModificarFicha.indexOf(self.tabTintas_2), _translate("Dialog", "Tintas", None))
        self.lblTipo_3.setText(_translate("Dialog", "Tipo", None))
        self.rbInterno_2.setText(_translate("Dialog", "Interno", None))
        self.rbExternoMod.setText(_translate("Dialog", "Externo", None))
        self.pbAniadirMallaMod.setText(_translate("Dialog", "Añadir Malla", None))
        self.pbEditarMallaMod.setText(_translate("Dialog", "Editar Malla", None))
        self.pbBorrarMallaMod.setText(_translate("Dialog", "Borrar Malla", None))
        self.tabModCarSec.setTabText(self.tabModCarSec.indexOf(self.tabMallas_2), _translate("Dialog", "Mallas", None))
        self.lblProveedorAdhLam_2.setText(_translate("Dialog", "Proveedor", None))
        self.lblAniloxAdhLam_2.setText(_translate("Dialog", "Anilox", None))
        self.pbAniadirAdhLamMod.setText(_translate("Dialog", "Añadir Adhesivo Laminacion", None))
        self.pbEditarAdhLamMod.setText(_translate("Dialog", "Editar Adhesivo Laminacion", None))
        self.pbBorrarAdhLamMod.setText(_translate("Dialog", "Borrar Adhesivo Laminacion", None))
        self.tabModCarSec.setTabText(self.tabModCarSec.indexOf(self.tabAdhesivoLaminacion_2), _translate("Dialog", "Adhesivo Laminacion", None))
        self.lblProveedorAdhCoFo_2.setText(_translate("Dialog", "Proveedor", None))
        self.lblAnchoAdhCoFo_2.setText(_translate("Dialog", "Anilox", None))
        self.pbAniadirAdhCoFoMod.setText(_translate("Dialog", "Añadir Adhesivo Cold Foil", None))
        self.pbEditarAdhCoFoMod.setText(_translate("Dialog", "Editar Adhesivo Cold Foil", None))
        self.pbBorrarAdhCoFoMod.setText(_translate("Dialog", "Borrar Adhesivo Cold Foil", None))
        self.tabModCarSec.setTabText(self.tabModCarSec.indexOf(self.tabAdhesivoColdFoil_2), _translate("Dialog", "Adhesivo Cold Foil", None))
        self.lblProveedorFilmMi_2.setText(_translate("Dialog", "Proveedor", None))
        self.lblAnchoFilmMi_2.setText(_translate("Dialog", "Ancho", None))
        self.pbAniadirFilmMiMod.setText(_translate("Dialog", "Añadir Film Micronaje", None))
        self.pbEditarFilmMiMod.setText(_translate("Dialog", "Editar Film Micronaje", None))
        self.pbBorrarFilmMiMod.setText(_translate("Dialog", "Borrar Film Micronaje", None))
        self.tabModCarSec.setTabText(self.tabModCarSec.indexOf(self.tabFilmMicronaje_2), _translate("Dialog", "Film Micronaje", None))
        self.rbCF.setText(_translate("Dialog", "Cold Foil", None))
        self.rbHS.setText(_translate("Dialog", "Hot Stamping", None))
        self.lblProveedorColdFoil_2.setText(_translate("Dialog", "Proveedor", None))
        self.lblAnchoColdFoil_2.setText(_translate("Dialog", "Ancho", None))
        self.pbAniadirColdFoilMod.setText(_translate("Dialog", "Añadir Cold Foil", None))
        self.pbEditarColdFoilMod.setText(_translate("Dialog", "Editar Cold Foil", None))
        self.pbBorrarColdFoilMod.setText(_translate("Dialog", "Borrar Cold Foil", None))
        self.tabModCarSec.setTabText(self.tabModCarSec.indexOf(self.tabColdFoil_2), _translate("Dialog", "Cold Foil", None))
        self.lblTipoTBarniz_2.setText(_translate("Dialog", "Tipo", None))
        self.lblProveedorTBarniz_2.setText(_translate("Dialog", "Proveedor", None))
        self.lblAniloxTBarniz_2.setText(_translate("Dialog", "Anilox", None))
        self.pbEditarTBarnizMod.setText(_translate("Dialog", "Editar Tipo de Barniz", None))
        self.pbBorrarTBarnizMod.setText(_translate("Dialog", "Borrar Tipo de Barniz", None))
        self.pbAniadirTBarnizMod.setText(_translate("Dialog", "Añadir Tipo de Barniz", None))
        self.tabModCarSec.setTabText(self.tabModCarSec.indexOf(self.tabTipoBarniz_2), _translate("Dialog", "Tipo de Barniz", None))
        self.lblProveedorTroquel_2.setText(_translate("Dialog", "Proveedor", None))
        self.lblObservaciones.setText(_translate("Dialog", "Observaciones", None))
        self.pbAniadirTroquelMod.setText(_translate("Dialog", "Añadir Troquel", None))
        self.pbEditarTroquelMod.setText(_translate("Dialog", "Editar Troquel", None))
        self.pbBorrarTroquelMod.setText(_translate("Dialog", "Borrar Troquel", None))
        self.tabModCarSec.setTabText(self.tabModCarSec.indexOf(self.tabTroquel_2), _translate("Dialog", "Troquel", None))
        self.tabModificarFicha.setTabText(self.tabModificarFicha.indexOf(self.tabCaracteristicas_2), _translate("Dialog", "Caracteristicas Adicionales", None))
        self.pbModificarFicha.setText(_translate("Dialog", "Terminar Modificacion", None))
        self.tabOpFichas.setTabText(self.tabOpFichas.indexOf(self.tabModificarficha), _translate("Dialog", "Modificar Ficha", None))
        self.groupBox.setTitle(_translate("Dialog", "Filtrar por", None))
        self.rbCategoria.setText(_translate("Dialog", "Categoria", None))
        self.rbPedidos.setText(_translate("Dialog", "Pedidos", None))
        self.rbEtiqueta.setText(_translate("Dialog", "Etiqueta", None))
        self.rbCliente.setText(_translate("Dialog", "Cliente", None))
        self.pbMostrarFicha.setText(_translate("Dialog", "Mostrar Ficha", None))
        self.tabOpFichas.setTabText(self.tabOpFichas.indexOf(self.tabConsultarFicha), _translate("Dialog", "Consultar Ficha", None))
        self.tabPrincipal.setTabText(self.tabPrincipal.indexOf(self.tabAdministrarFichas), _translate("Dialog", "Administrar Fichas Tecnicas", None))
        self.pbAniadirCategoria.setText(_translate("Dialog", "Añadir Categoria", None))
        self.pbEditarCategoria.setText(_translate("Dialog", "Editar Categoria", None))
        item = self.twCatergoria.horizontalHeaderItem(0)
        item.setText(_translate("Dialog", "Nombre", None))
        self.tabPrincipal.setTabText(self.tabPrincipal.indexOf(self.tabAdministrarCategorias), _translate("Dialog", "Administrar Categorias", None))
        self.lblRut.setText(_translate("Dialog", "Rut Cliente", None))
        self.lblNombre.setText(_translate("Dialog", "Nombre Cliente", None))
        self.pbAniadirCliente.setText(_translate("Dialog", "Añadir Cliente", None))
        item = self.twCliente.horizontalHeaderItem(0)
        item.setText(_translate("Dialog", "Rut ", None))
        item = self.twCliente.horizontalHeaderItem(1)
        item.setText(_translate("Dialog", "Nombre", None))
        self.pbEditarCliente.setText(_translate("Dialog", "Editar Cliente", None))
        self.tabPrincipal.setTabText(self.tabPrincipal.indexOf(self.tabAdministraClientes), _translate("Dialog", "Administrar Clientes", None))
        self.pbAniadirMaquina.setText(_translate("Dialog", "Añadir Maquina", None))
        self.pbEditarMaquina.setText(_translate("Dialog", "Editar Maquina", None))
        item = self.twMaquina.horizontalHeaderItem(0)
        item.setText(_translate("Dialog", "Codigo", None))
        self.tabPrincipal.setTabText(self.tabPrincipal.indexOf(self.tabAdministrarMaquinas), _translate("Dialog", "Administrar Maquinas", None))

